---

- name: install git
  package:
    name: 
        - git
    state: present

- name: clone repo on bootstrap node
  git:
    repo: 'https://github.com/OlafRadicke/play_with_k8s.git'
    dest: /srv/play_with_k8s

- name: copy sub playbook
  copy:
      src: k8s_nodes_setup.yml
      dest: /srv/play_with_k8s/ansible_playbooks/rancher_k8s/k8s_nodes_setup.yml
    
- name: start sub playbook
  shell: "ansible-playbook -i ./hosts k8s_nodes_setup.yml"
  args:
    chdir: "/srv/play_with_k8s/ansible_playbooks/rancher_k8s/"